blueprint:
  name: CO2 Presence RGB Warning Light (Stable & Fixed)
  description: >
    RGB-Licht, das nur bei Präsenz stufenlos röter/heller wird,
    abhängig vom CO2-Wert. Kein Flackern, keine unnötigen Updates.
  domain: automation

  input:
    co2_sensor:
      name: CO2 Sensor
      selector:
        entity:
          domain: sensor

    presence_sensor:
      name: Präsenzsensor
      selector:
        entity:
          domain: binary_sensor

    target_light:
      name: RGB-Licht
      selector:
        entity:
          domain: light

    co2_min:
      name: Untere CO2-Schwelle
      default: 800
      selector:
        number:
          min: 400
          max: 2000

    co2_max:
      name: Obere CO2-Schwelle
      default: 2000
      selector:
        number:
          min: 1000
          max: 3000

    min_brightness:
      name: Minimale Helligkeit (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100

    max_brightness:
      name: Maximale Helligkeit (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100

mode: restart

trigger:
  - platform: state
    entity_id: !input co2_sensor
  - platform: state
    entity_id: !input presence_sensor

variables:
  # YAML Variable → Template darf das nutzen
  co2_entity: !input co2_sensor
  presence_entity: !input presence_sensor
  light: !input target_light

  co2_min_val: !input co2_min
  co2_max_val: !input co2_max
  min_brightness_val: !input min_brightness
  max_brightness_val: !input max_brightness

  # Werte aus dem System lesen
  co2: "{{ states(co2_entity) | float(0) }}"
  presence: "{{ is_state(presence_entity, 'on') }}"

  # 0–1 Skala
  factor: >-
    {% if co2 < co2_min_val %}
      0
    {% elif co2 >= co2_max_val %}
      1
    {% else %}
      {{ (co2 - co2_min_val) / (co2_max_val - co2_min_val) }}
    {% endif %}

  # Zielwerte
  target_hue: "{{ 120 - (120 * factor) }}"
  target_brightness: >
    {{ (min_brightness_val + factor * (max_brightness_val - min_brightness_val)) | round(0) }}

  # Aktuelle Werte lesen
  current_brightness: "{{ (state_attr(light, 'brightness') or 0) | int }}"
  current_brightness_pct: "{{ (current_brightness / 255 * 100) | round(0) }}"
  current_hue: "{{ state_attr(light, 'hs_color')[0] if state_attr(light, 'hs_color') else 0 }}"

action:
  - choose:

      # 1) Präsenz aus → Licht aus
      - conditions: "{{ not presence }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input target_light

      # 2) Präsenz an
      - conditions: "{{ presence }}"
        sequence:

          # 2a) CO₂ unter Untergrenze → AUS
          - choose:
              - conditions: "{{ co2 < co2_min_val }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input target_light

          # 2b) CO₂ >= Untergrenze → nur ändern, wenn nötig
          - condition: template
            value_template: "{{ co2 >= co2_min_val }}"

          # prüfen, ob Änderung nötig ist
          - condition: template
            value_template: >
              {{ (current_brightness_pct | int != target_brightness | int)
                 or ((current_hue | float) | round(1) != (target_hue | float) | round(1)) }}

          # Änderung senden
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              hs_color:
                - "{{ target_hue }}"
                - 100
              brightness_pct: "{{ target_brightness }}"
              transition: 2